name: fetch-dhi-manifest
on:
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    container:
      credentials:
        username: 0mniteck42
        password: ${{ secrets.DOCKER }}
      image: docker://dhi.io/debian-base@sha256:62bc0610151db7155b7225f1a03c299bf109ab0b884da6777d1f808c7834d4ea # trixie-debian13-dev (fetched 2026-06-25)
    steps:
      - name: Get trixie-debian13-dev digest
        run: |
          TOKEN=$(curl -sf -u "0mniteck42:$DOCKER_PASS" 'https://dhi.io/token?service=registry.docker.io&scope=repository:debian-base:pull' | python3 -c 'import sys,json; print(json.load(sys.stdin)["token"])' )
          curl -sI -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.oci.image.manifest.v1+json" https://dhi.io/v2/debian-base/manifests/trixie-debian13-dev | grep -i docker-content-digest
        env:
          DOCKER_PASS: ${{ secrets.DOCKER }}
